sharelatex:
  build: ./sharelatex
  ports:
    - "80:80"
#  volumes:
#    - /docker/sharelatex/dat:/var/lib/sharelatex
  links:
    - sharelatex-db:db
    - sharelatex-redis:redis
  environment:
    - SHARELATEX_MONGO_URL=mongodb://db/sharelatex
    - SHARELATEX_REDIS_HOST=redis
    - SHARELATEX_APP_NAME="Test"
    - SHARELATEX_NAV_TITLE="Test 2"

sharelatex-db:
  build: /docker/dtu-enote/components/mongodb
  expose:
    - "27017"
#  volumes:
#    - /docker/sharelatex/mongodb:/var/lib/mongodb
#    - /docker/sharelatex/mongolog:/var/log/mongodb

sharelatex-redis:
  image: redis
  expose:
    - "6379"
